version: '3.1'

services:
  db:
    image: mysql
    restart: always
    env_file:
      mysql.env
    ports:
      - '3307:3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d/:ro

volumes:
  my-db: